### ISSUE TITLE
Please mention Proxmark3 and Iceman Firmware, then link to their URLs in the README.

### ISSUE THREAD

**Issue by jpluimers** [aoxhwjfoavdlhsvfpzha/PM3-Scripts#1]
Since I did not know what PM3 was, I Googled which (because I'm in The Netherlands), it returned.

By now I know this repository is about [Proxmark 3 device](https://proxmark.com/proxmark-3-hardware/proxmark-3) and the [Proxmark 3 Iceman Firmware](https://github.com/RfidResearchGroup/proxmark3).

Could you please mention both of these in the repository description, and link to their respective URLs  in the README?

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
Good idea
